BaiMau_62130808/Controllers/SinhViens62130808Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BaiMau_62130808.Models;

namespace BaiMau_62130808.Controllers
{
    public class SinhViens62130808Controller : Controller
    {
        private BAIMAU_62130808Entities db = new BAIMAU_62130808Entities();

        // GET: SinhViens62130808
        public ActionResult GioiThieu()
        {
            return View();
        }
        
        // GET: SinhVien0720_62130808
        public ActionResult Index()
        {
            var sinhViens = db.SinhViens.Include(s => s.Lop);
            return View(sinhViens.ToList());
        }

        // GET: SinhVien0720_62130808/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SinhVien sinhVien = db.SinhViens.Find(id);
            if (sinhVien == null)
            {
                return HttpNotFound();
            }
            return View(sinhVien);
        }
        public ActionResult TimKiem()
        {
            var sinhViens = db.SinhViens.Include(s => s.Lop);
            return View(sinhViens.ToList());
        }
        [HttpPost]
        public ActionResult TimKiem(string maSV/*, string HoTen = ""*/)
        {

            //var sinhViens = db.SinhViens.SqlQuery("exec NhanVien_DS '"+maNV+"' ");
            /// var sinhViens = db.SinhViens.SqlQuery("SELECT * FROM NhanVien WHERE MaNV='" + maNV + "'");
            //var sinhViens = db.SinhViens.Where(abc => abc.MaNV == maNV); //Tìm chính xác
            //var sinhViens = db.SinhViens.Where(abc => abc.MaSV.Contains(maSV)); //Tìm gần chính xác

            /*ViewBag.MaSV = MaSV;
            ViewBag.HoTen = HoTen;
            var sinhViens = db.SinhViens.SqlQuery("SinhVien_TimKiem'" + MaSV + "','" + HoTen + "'");
            if (sinhViens.Count() == 0)
                ViewBag.TB = "Không có thông tin tìm kiếm.";*/
            var sinhViens = db.SinhViens.Where(abc => abc.MaSV.Contains(maSV));
            return View(sinhViens.ToList());
        }
        [HttpGet]

        public ActionResult TimKiem_62130808(string maSV = "", string hoTen = "")
        {
            ViewBag.MaLop = new SelectList(db.Lops, "MaLop", "TenLop");
            var sinhViens = db.Lops.SqlQuery("SinhVien_TimKiem'" + maSV + "','" + hoTen + "'");
            if (sinhViens.Count() == 0)
                ViewBag.TB = "Không có thông tin tìm kiếm.";
            return View(sinhViens.ToList());
        }

        // GET: SinhVien0720_62130808/Create
        public ActionResult Create()
        {
            ViewBag.MaLop = new SelectList(db.Lops, "MaLop", "TenLop");
            return View();
        }

        // POST: SinhVien0720_62130808/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSV,HoSV,TenSV,NgaySinh,GioiTinh,AnhSV,DiaChi,MaLop")] SinhVien sinhVien)
        {
            if (ModelState.IsValid)
            {
                db.SinhViens.Add(sinhVien);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaLop = new SelectList(db.Lops, "MaLop", "TenLop", sinhVien.MaLop);
            return View(sinhVien);
        }

        // GET: SinhVien0720_62130808/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SinhVien sinhVien = db.SinhViens.Find(id);
            if (sinhVien == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLop = new SelectList(db.Lops, "MaLop", "TenLop", sinhVien.MaLop);
            return View(sinhVien);
        }

        // POST: SinhVien0720_62130808/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSV,HoSV,TenSV,NgaySinh,GioiTinh,AnhSV,DiaChi,MaLop")] SinhVien sinhVien)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sinhVien).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLop = new SelectList(db.Lops, "MaLop", "TenLop", sinhVien.MaLop);
            return View(sinhVien);
        }

        // GET: SinhVien0720_62130808/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SinhVien sinhVien = db.SinhViens.Find(id);
            if (sinhVien == null)
            {
                return HttpNotFound();
            }
            return View(sinhVien);
        }

        // POST: SinhVien0720_62130808/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            SinhVien sinhVien = db.SinhViens.Find(id);
            db.SinhViens.Remove(sinhVien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BaiMau_62130808/Views/SinhViens62130808/Create.cshtml
@model BaiMau_62130808.Models.SinhVien

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thêm mới</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SinhVien</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaSV, "Mã sinh viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoSV, "Họ sinh viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSV, "Tên sinh viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, "Ngày sinh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, "Giới tính", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    Nam @Html.RadioButtonFor(model => model.GioiTinh, "True", new { @checked = "checked" }) &nbsp;
                    Nữ @Html.RadioButtonFor(model => model.GioiTinh, "False")
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhSV, "Ảnh sinh viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnhSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, "Địa chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLop, "Lớp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLop", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLop, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BaiMau_62130808/Views/SinhViens62130808/Delete.cshtml
@model BaiMau_62130808.Models.SinhVien

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    string gtinh = "";
}

<h2>Xoá</h2>

<h3>Xác nhận xoá?</h3>
<div>
    <h4>SinhVien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Họ sinh viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoSV)
        </dd>

        <dt>
            Tên sinh viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSV)
        </dd>

        <dt>
            Ngày sinh
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            Giới tính
        </dt>

        <dd>
            @{if (Model.GioiTinh == true)
                { gtinh = "Nam"; }
                else
                { gtinh = "Nữ"; }
            }
            @gtinh
        </dd>

        <dt>
            Ảnh sinh viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhSV)
        </dd>

        <dt>
            Địa chỉ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            Lớp
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lop.TenLop)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BaiMau_62130808/Views/SinhViens62130808/Details.cshtml
@model BaiMau_62130808.Models.SinhVien

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    string gtinh = "";
}

<h2>Chi tiết</h2>

<div>
    <h4>SinhVien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Họ sinh viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoSV)
        </dd>

        <dt>
            Tên sinh viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSV)
        </dd>

        <dt>
            Ngày sinh
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            Giới tính
        </dt>

        <dd>
            @{if (Model.GioiTinh == true)
                { gtinh = "Nam"; }
                else
                { gtinh = "Nữ"; }
            }
            @gtinh
        </dd>

        <dt>
            Ảnh sinh viên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhSV)
        </dd>

        <dt>
            Địa chỉ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            Lớp
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lop.TenLop)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaSV }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BaiMau_62130808/Views/SinhViens62130808/Edit.cshtml
@model BaiMau_62130808.Models.SinhVien

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Chỉnh sửa</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SinhVien</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaSV)

        <div class="form-group">
            @Html.LabelFor(model => model.HoSV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.GioiTinh)
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhSV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnhSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLop, "MaLop", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLop", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLop, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BaiMau_62130808/Views/SinhViens62130808/GioiThieu.cshtml
@{
    ViewBag.Title = "GioiThieu";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>ĐẶC TẢ PHẦN MỀM</h2>
<p>
    Để quản lý thông tin nhân viên trong hệ thống, người ta xây dựng website theo các yêu
    cầu gợi ý sau:
</p>
<ol type="a">
    <li>
        Thiết kế CSDL có tên QLNV_MãSV gồm 2 bảng dữ liệu sau:
        Phòng ban (<b>Mã phòng ban</b>, Tên phòng ban)
        Nhân viên (<b>Mã NV</b>, Họ NV, Tên NV, Giới tính, Ngày sinh, Lương, Ảnh NV, Địa chỉ, Mã phòng ban)
    </li>
    <li>Tạo Entity Data Model (EDM) có tên ModelQLNV_MãSV cho CSDL trên.</li>
    <li>
        Xây dựng các chức năng cho phép người quản trị quản lý các thông tin: Phòng ban, Nhân viên
        (thêm, sửa, xóa và hiện thị danh sách).
    </li>
    <li>
        Tìm kiếm thông tin liên quan đến nhân viên: Mã nhân viên, họ tên, giới tính, địa chỉ, phòng ban, …
    </li>
</ol>

BaiMau_62130808/Views/SinhViens62130808/Index.cshtml
@model IEnumerable<BaiMau_62130808.Models.SinhVien>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TenSV", rowsPerPage: 2);
    @Scripts.Render("~/Scripts/jquery-1.6.2.min.js")
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div id="gridContent">
    @ViewBag.TB
    @grid.GetHtml(
        tableStyle: "table table-bordered table-hover",
        footerStyle: "grid-footer",
        fillEmptyRows: true,
        mode: WebGridPagerModes.Numeric,
        alternatingRowStyle: "alternatingRowStyle",
        columns: new[]  // colums in grid
        {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("MaSV","Mã sinh viên"), //the model fields to display
            grid.Column("HoSV","Họ sinh viên"  ),
            grid.Column("TenSV","Tên sinh viên"),
            grid.Column("NgaySinh","Ngày sinh",format:@<text> @item.NgaySinh.ToString("dd/MM/yyyy")</text>),
            grid.Column("GioiTinh","Giới tính",format: (@item) => @item.GioiTinh==true?"Nam":"Nữ"),
            grid.Column("AnhSV","Ảnh sinh viên"@*format:@<text> @item.Luong.ToString("#,##0")</text>*@),
            grid.Column("DiaChi","Địa chỉ"),
            grid.Column("Lop.TenLop","Lớp"),
            /*grid.Column(format: (item) => Html.ActionLink("Cập nhật", "Edit", "SinhVien0720_62130808",new { id = item.MaSV },"SinhVien0720_62130808Controller")),
            grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","SinhVien0720_62130808", new { id = item.MaSV },"SinhVien0720_62130808Controller")),
            grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","SinhVien0720_62130808", new { id = item.MaSV },"SinhVien0720_62130808Controller")),*/
            grid.Column("Chức năng", format: @<text>
                <a href="@Url.Action("Edit", new { id = item.MaSV})" class="edit-btn"><abbr title="Cập nhật dữ liệu"><img src="/images/edit.png" width="20" height="20" /></abbr></a>
                <a href="@Url.Action("Details", new { id = item.MaSV})" class="edit-btn"><abbr title="Xem chi tiết"><img src="/images/details.png" width="20" height="20" /></abbr></a>
                <a href="@Url.Action("Delete", new { id = item.MaSV})" class="edit-btn"><abbr title="Xóa dữ liệu"><img src="/images/delete.png" width="20" height="20" /></abbr></a>
            </text>
),
}
)
</div>

BaiMau_62130808/Views/SinhViens62130808/TimKiem.cshtml
@model IEnumerable<BaiMau_62130808.Models.SinhVien>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var grid = new WebGrid(Model, canPage: true, /*defaultSort: "TenSV",*/ rowsPerPage: 2);
    string gtinh = "";
    var i = 0;
    @Scripts.Render("~/Scripts/jquery-1.6.2.min.js")

}




@using (Html.BeginForm())
{
    <input type="text" name="maSV" />
    <input type="submit" value="Tìm kiếm" />
    <h3>DANH SÁCH NHÂN VIÊN</h3>

    <p>
        @Html.ActionLink("Thêm mới", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                STT
            </th>
            <th>
                Mã SV
            </th>
            <th>
                Họ sinh viên
            </th>
            <th>
                Tên sinh viên
            </th>
            <th>
                Giới tính
            </th>
            <th>
                Ngày sinh
            </th>
            <th>
                Ảnh NV
            </th>
            <th>
                Địa chỉ
            </th>
            <th>
                Phòng ban
            </th>
            <th>Chức năng</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @{i++;}
                    @i
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaSV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HoSV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TenSV)
                </td>
                <td>
                    @{if (item.GioiTinh == true)
                        { gtinh = "Nam"; }
                        else
                        { gtinh = "Nữ"; }
                    }
                    @gtinh

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgaySinh)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AnhSV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DiaChi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaLop)
                </td>
                <td>
                    @Html.ActionLink("Sửa", "Edit", new { id = item.MaSV }) |
                    @Html.ActionLink("Xem chi tiết", "Details", new { id = item.MaSV }) |
                    @Html.ActionLink("Xóa", "Delete", new { id = item.MaSV })
                </td>
            </tr>
        }

    </table>

}

BaiMau_62130808/Views/SinhViens62130808/TimKiem_62130808.cshtml
@model IEnumerable<BaiMau_62130808.Models.SinhVien>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var grid = new WebGrid(Model, canPage: true, /*defaultSort: "TenSV",*/ rowsPerPage: 2);
    string gtinh = "";
    var i = 0;
    @Scripts.Render("~/Scripts/jquery-1.6.2.min.js")

}

<html>
<head>
    <style type="text/css">
        .btn {
            background-color: #0073A5;
            color: #fff;
            font-size: 16px;
            font-weight: bold;
            text-decoration: none;
            padding: 5px 15px;
            border-radius: 5px;
            margin-left: 5px;
            transition: all .3s ease;
        }

            .btn:hover {
                background-color: #fff;
                color: #0073A5;
                transition: all .3s ease;
            }
    </style>
</head>
<body>
    <div>
        @using (Html.BeginForm("TimKiem_62130808", "SinhViens62130808", FormMethod.Get))
        {
            @Html.AntiForgeryToken()

            <table class="table1" align="center">
                <tr>
                    <td>Mã sinh viên</td>
                    <td>
                        <input type="text" name="MaSV" value="@ViewBag.MaSV" />
                    </td>
                </tr>
                <tr>
                        <td>Họ tên</td>
                        <td>
                            <input type="text" name="HoTen" value="@ViewBag.HoTen" />
                        </td>
                    </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" name="submit" value="Tìm kiếm" />
                        <input type="button" name="Nhapmoi" value="Nhập mới" onclick="location.href='@Url.Action("TimKiem_62130808", "SinhViens62130808/TimKiem_62130808")'" />
                    </td>
                </tr>
            </table>
        }
    </div>
    <div id="gridContent">
        @ViewBag.TB
        @grid.GetHtml(
            tableStyle: "table table-bordered table-hover",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
            columns: new[]  // colums in grid
            {
                grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
                grid.Column("MaSV","Mã sinh viên"), //the model fields to display
                grid.Column("HoSV","Họ sinh viên"  ),
                grid.Column("TenSV","Tên sinh viên"),
                grid.Column("NgaySinh","Ngày sinh",format:@<text> @item.NgaySinh.ToString("dd/MM/yyyy")</text>),
grid.Column("GioiTinh","Giới tính",format: (@item) => @item.GioiTinh==true?"Nam":"Nữ"),
grid.Column("AnhSV","Ảnh sinh viên"@*format:@<text> @item.Luong.ToString("#,##0")</text>*@),
grid.Column("DiaChi","Địa chỉ"),
grid.Column("Lop.TenLop","Lớp"),
/*grid.Column(format: (item) => Html.ActionLink("Cập nhật", "Edit", "SinhVien0720_62130808",new { id = item.MaSV },"SinhVien0720_62130808Controller")),
grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","SinhVien0720_62130808", new { id = item.MaSV },"SinhVien0720_62130808Controller")),
grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","SinhVien0720_62130808", new { id = item.MaSV },"SinhVien0720_62130808Controller")),*/
grid.Column("Chức năng", format: @<text>
    <a href="@Url.Action("Edit", new { id = item.MaSV})" class="edit-btn"><abbr title="Cập nhật dữ liệu"><img src="/images/edit.png" width="20" height="20" /></abbr></a>
    <a href="@Url.Action("Details", new { id = item.MaSV})" class="edit-btn"><abbr title="Xem chi tiết"><img src="/images/details.png" width="20" height="20" /></abbr></a>
    <a href="@Url.Action("Delete", new { id = item.MaSV})" class="edit-btn"><abbr title="Xóa dữ liệu"><img src="/images/delete.png" width="20" height="20" /></abbr></a>
</text>
),
}
)
    </div>
</body>
</html>