KaraokeProject-master/KaraokeProject/Models/PhongHat.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaraokeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongHat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhongHat()
        {
            this.DatPhongs = new HashSet<DatPhong>();
        }
    
        public string MaPhongHat { get; set; }
        public string TenPhongHat { get; set; }
        public string LoaiPhong { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatPhong> DatPhongs { get; set; }
        public virtual LoaiPhong LoaiPhong1 { get; set; }
        public virtual TrangThai TrangThai1 { get; set; }
    }
}

KaraokeProject-master/KaraokeProject/Controllers/PhongHatsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KaraokeProject.Models;

namespace KaraokeProject.Controllers
{
    public class PhongHatsController : Controller
    {
        private QLKaraokeEntities db = new QLKaraokeEntities();

        string getMa(string loai)
        {
            var maMax = db.PhongHats.ToList().Select(n => n.MaPhongHat).Max();
            int ma = int.Parse(maMax.Substring(2)) + 1;
            string type = String.Concat("0", ma.ToString());
            return loai + type.Substring(ma.ToString().Length - 1);
        }

        // GET: PhongHats
        public ActionResult Index()
        {
            var phongHats = db.PhongHats.Include(p => p.LoaiPhong1).Include(p => p.TrangThai1);
            return View(phongHats.ToList());
        }

        // GET: PhongHats/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhongHat phongHat = db.PhongHats.Find(id);
            if (phongHat == null)
            {
                return HttpNotFound();
            }
            return View(phongHat);
        }

        // GET: PhongHats/Create
        public ActionResult Create()
        {
            ViewBag.ID = getMa("PH");
            ViewBag.LoaiPhong = new SelectList(db.LoaiPhongs, "MaLoaiPhong", "TenLoaiPhong");
            var trangThais = db.TrangThais.Where(tt => tt.MaTrangThai == "SS" || tt.MaTrangThai == "HD" || tt.MaTrangThai == "NC");
            ViewBag.TrangThai = new SelectList(trangThais, "MaTrangThai", "TenTrangThai");
            return View();
        }

        // POST: PhongHats/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaPhongHat,TenPhongHat,LoaiPhong,TrangThai")] PhongHat phongHat)
        {
            string id = getMa("PH");
            if (ModelState.IsValid)
            {
                phongHat.MaPhongHat = id;
                db.PhongHats.Add(phongHat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LoaiPhong = new SelectList(db.LoaiPhongs, "MaLoaiPhong", "TenLoaiPhong", phongHat.LoaiPhong);
            var trangThais = db.TrangThais.Where(tt => tt.MaTrangThai == "SS" || tt.MaTrangThai == "HD" || tt.MaTrangThai == "NC");
            ViewBag.TrangThai = new SelectList(trangThais, "MaTrangThai", "TenTrangThai", phongHat.TrangThai);
            return View(phongHat);
        }

        // GET: PhongHats/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhongHat phongHat = db.PhongHats.Find(id);
            ViewBag.ID = phongHat.MaPhongHat;
            if (phongHat == null)
            {
                return HttpNotFound();
            }
            ViewBag.LoaiPhong = new SelectList(db.LoaiPhongs, "MaLoaiPhong", "TenLoaiPhong", phongHat.LoaiPhong);
            var trangThais = db.TrangThais.Where(tt => tt.MaTrangThai == "SS" || tt.MaTrangThai == "HD" || tt.MaTrangThai == "NC");
            ViewBag.TrangThai = new SelectList(trangThais, "MaTrangThai", "TenTrangThai", phongHat.TrangThai);
            return View(phongHat);
        }

        // POST: PhongHats/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaPhongHat,TenPhongHat,LoaiPhong,TrangThai")] PhongHat phongHat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(phongHat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LoaiPhong = new SelectList(db.LoaiPhongs, "MaLoaiPhong", "TenLoaiPhong", phongHat.LoaiPhong);
            ViewBag.TrangThai = new SelectList(db.TrangThais, "MaTrangThai", "TenTrangThai", phongHat.TrangThai);
            return View(phongHat);
        }

        // GET: PhongHats/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhongHat phongHat = db.PhongHats.Find(id);
            ViewBag.ID = phongHat.TenPhongHat;
            if (phongHat == null)
            {
                return HttpNotFound();
            }
            return View(phongHat);
        }

        // POST: PhongHats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            PhongHat phongHat = db.PhongHats.Find(id);
            db.PhongHats.Remove(phongHat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KaraokeProject-master/KaraokeProject/Views/PhongHats/Create.cshtml
@model KaraokeProject.Models.PhongHat

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content container-fluid">
    <div class="page-header">
        <div class="row align-items-center">
            <div class="col">
                <h3 class="page-title mt-5">Thêm phòng mới</h3>
            </div>
        </div>
    </div>
    @using (Html.BeginForm("Create", "PhongHats", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="row">
            <div class="col-lg-12">
                <div class="row formtype">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.MaPhongHat, "Mã Phòng hát")
                            <input type="text" readonly disabled class="form-control" value="@ViewBag.ID" />
                            @Html.ValidationMessageFor(model => model.MaPhongHat, "", new { @class = "w3-text-red" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.TenPhongHat, "Tên Phòng hát")
                            @Html.EditorFor(model => model.TenPhongHat, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenPhongHat, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.LoaiPhong, "Loại phòng")
                            @Html.DropDownList("LoaiPhong", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.LoaiPhong, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.TrangThai, "Trạng thái")
                            @Html.DropDownList("TrangThai", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="w3-center">
            <input type="submit" value="Thêm" class="btn btn-primary w3-margin-right" />
            <input type="button" value="Hủy" class="btn btn-danger" onclick="window.location.href = '@Url.Action("Index", "PhongHats")'" />
        </div>
    }
</div>

KaraokeProject-master/KaraokeProject/Views/PhongHats/Delete.cshtml
@model KaraokeProject.Models.PhongHat

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content container-fluid">
    <div class="page-header">
        <div class="row align-items-center">
            <div class="col w3-center">
                <h3 class="page-title mt-5">Xóa Phòng hát "@ViewBag.ID?"</h3>
            </div>
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="w3-center">
            <input type="submit" value="Xóa" class="btn btn-danger w3-margin-right" />
            <input type="button" value="Hủy" class="btn btn-secondary" onclick="window.location.href = '@Url.Action("Index", "PhongHats")'" />
        </div>
    }
</div>

KaraokeProject-master/KaraokeProject/Views/PhongHats/Details.cshtml
@model KaraokeProject.Models.PhongHat

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>PhongHat</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenPhongHat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenPhongHat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiPhong1.TenLoaiPhong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiPhong1.TenLoaiPhong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrangThai1.TenTrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrangThai1.TenTrangThai)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaPhongHat }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KaraokeProject-master/KaraokeProject/Views/PhongHats/Edit.cshtml
@model KaraokeProject.Models.PhongHat

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="content container-fluid">
    <div class="page-header">
        <div class="row align-items-center">
            <div class="col">
                <h3 class="page-title mt-5">Chỉnh sửa phòng hát</h3>
            </div>
        </div>
    </div>
    @using (Html.BeginForm("Edit", "PhongHats", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="row">
            <div class="col-lg-12">
                <div class="row formtype">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.MaPhongHat)
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.MaPhongHat, "Mã Phòng hát")
                            <input type="text" readonly disabled class="form-control" value="@ViewBag.ID" />
                            @Html.ValidationMessageFor(model => model.MaPhongHat, "", new { @class = "w3-text-red" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.TenPhongHat, "Tên Phòng hát")
                            @Html.EditorFor(model => model.TenPhongHat, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenPhongHat, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.LoaiPhong, "Loại phòng")
                            @Html.DropDownList("LoaiPhong", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.LoaiPhong, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.TrangThai, "Trạng thái")
                            @Html.DropDownList("TrangThai", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="w3-center">
            <input type="submit" value="Thêm" class="btn btn-primary w3-margin-right" />
            <input type="button" value="Hủy" class="btn btn-danger" onclick="window.location.href = '@Url.Action("Index", "PhongHats")'" />
        </div>
    }
</div>

KaraokeProject-master/KaraokeProject/Views/PhongHats/Index.cshtml
@model IEnumerable<KaraokeProject.Models.PhongHat>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    int index = 0;
}

<div class="content container-fluid">
    <div class="page-header">
        <div class="row align-items-center">
            <div class="col">
                <div class="mt-5">
                    <h4 class="card-title float-left mt-2">Danh sách Phòng hát</h4>
                    <a href="@Url.Action("Create","PhongHats")" class="btn btn-primary float-right veiwbutton">Thêm phòng</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="card card-table">
                <div class="card-body booking_card">
                    <div class="table-responsive">
                        <table class="datatable table table-stripped table table-hover table-center mb-0">
                            <thead>
                                <tr>
                                    <th>STT</th>
                                    <th>Mã phòng</th>
                                    <th>Tên phòng</th>
                                    <th>Trạng thái</th>
                                    <th class="text-right">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @{
                                                index++;

                                            }
                                            @index
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.MaPhongHat)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.TenPhongHat)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.TrangThai1.TenTrangThai)
                                        </td>
                                        <td class="text-right">
                                            <div class="dropdown dropdown-action">
                                                <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                                    <i class="fas fa-ellipsis-v ellipse_color"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a class="dropdown-item" href="@Url.Action("Edit","PhongHats", new { id = item.MaPhongHat })">
                                                        <i class="fas fa-pencil-alt m-r-5"></i> Sửa      
                                                    </a>
                                                    <a class="dropdown-item" href="@Url.Action("Delete","PhongHats", new { id = item.MaPhongHat })">
                                                        <i class="fas fa-trash-alt m-r-5"></i> Xóa      
                                                    </a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>